server:
  port: 8081
spring:
  application:
    name: rag
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      model: gpt-4-o
      embedding-model: text-embedding-ada-002
      max-tokens: 1000
      temperature: 0.7
    vectorstore:
      milvus:
        client:
          host: "172.16.16.162"
          port: 19530
          username: "root"
          password: "Milvus"
        databaseName: "mvs"
        embeddingDimension: 1536